import type { NextPage } from 'next'
import Head from 'next/head'

const About: NextPage = () => {
  const sidebar = true;
  return (
    <div>
      <Head>
        <title>About | AptosKorea</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline">
          About page
        </h1>
      </main>
    </div>
  )
}
export default About
